### ISSUE TITLE
WAYWindow.m missing ?

### ISSUE THREAD

**Issue by laurentsifre** [weAreYeah/WAYAppStoreWindow#1]
clang: error: no such file or directory: '/Users/laurentsifre/Downloads/WAYWindow/WAYWindow/WAYWindow.m'

**Comment by raffael** [comment]
You need to add `WAYWindow` to your project, which is not part of the repository.
https://github.com/weAreYeah/WAYWindow

**Comment by laurentsifre** [comment]
thanks !
